### ISSUE TITLE
SubmitRoutine issue

### ISSUE THREAD

**Issue by MartorelliLuca** [GymBuddy-Corporation/GymBuddyProject#1]
Nel metodo submitRoutine di SatisfyWorkoutRequestsController, quando gli chiedo di stampare tutti gli esercizi che ho caricato nell'interfaccia precedente, mi stampa solo gli esercizi che vedeva per ultimo nell'interfaccia.
Esempio: aggiungo Dips (lunedi), Tricep Pushdown (giovedi), Shoulder Press(sabato) (con relativi sets, ...), in giorni diversi. Clicco su Submit e mi stampa a schermo che ha aggiunto SOLO l'ultimo esercizio che vedevi nell'interfaccia avendo cliccato sul suo giorno (nel caso descritto è Shoulder press che ho aggiunto per ultimo di sabato).

**Comment by NomeMio** [comment]
Dopo mi ci metto @MartorelliLuca

**Comment by MartorelliLuca** [comment]
forse ho risolto, tranquillo. Ti aggiorno.

**Comment by NomeMio** [comment]
> forse ho risolto, tranquillo. Ti aggiorno.

Ok dimmi se ti serve una mano che ora mi metto al pc

**Comment by MartorelliLuca** [comment]
issue risolto

**Comment by MartorelliLuca** [comment]
resolved issue.
